---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Weber State IEEE Student Branch"
keywords:    "electronics, electrical engineering, computer engineering, weber state, ieee, student branch"
description: "A single-page site for the Weber State IEEE student branch"
source_link: "https://github.com/weberieee/weberieee.github.io"
favicon:     "img/favicon.png"
touch_icon:  "img/apple-touch-icon.png"



### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#492365'
  orange:    '#d25d12'
  turquoise: '#0fbfcf'
  grey:      '#4b4945'

kramdown:
  auto_ids:  false



